# Generated by Django 3.1.4 on 2021-01-18 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('gallery_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Gallery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_number', models.AutoField(primary_key=True, serialize=False)),
                ('image_name', models.CharField(blank=True, max_length=50, null=True)),
                ('image_path', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Image',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=30, null=True)),
                ('user_paswd', models.CharField(blank=True, max_length=30, null=True)),
                ('user_email', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'User',
                'managed': False,
            },
        ),
    ]
