# Generated by Django 3.1.5 on 2021-01-25 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mia', '0002_gallery_image_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
